export interface Paper {
	id: number;
	subject: string;
	board: string;
	year: number;
	season: string;
	paper: string;
	totalMarks?: number; // Now optional as it will be calculated
	questions: Question[]; // Questions for this paper
	url?: string; // Optional URL to the paper
	markschemeUrl?: string; // Optional URL to the mark scheme
}

export interface Question {
	id: string; // Changed from number to string to support formats like "1a", "1.2", etc.
	marks: number;
	displayName?: string; // Optional display name if different from id
}

export const pastPapers: Paper[] = [
	{
		id: 1,
		subject: 'cs',
		board: 'ocr',
		year: 2023,
		season: 'Summer',
		paper: 'H446/01 Computer Systems',
		url: "https://www.ocr.org.uk/Images/703780-question-paper-computer-systems.pdf",
		markschemeUrl: "https://www.ocr.org.uk/Images/703953-mark-scheme-computer-systems.pdf",
		questions: [
			{ id: '1ai', marks: 1 },
			{ id: '1aii', marks: 4 },
			{ id: '1iii', marks: 3 },
			{ id: '1b', marks: 3 },
			{ id: '1c', marks: 2 },
			{ id: '1di', marks: 3 },
			{ id: '1dii', marks: 2 },
			{ id: '1diii', marks: 2 },
			{ id: '1div', marks: 3 },
			{ id: '1ei', marks: 1 },
			{ id: '1eii', marks: 6 },
			{ id: '1f', marks: 3 },
			{ id: '1g', marks: 9 },
			{ id: '2a', marks: 5 },
			{ id: '2bi', marks: 3 },
			{ id: '2bii', marks: 3 },
			{ id: '2biii', marks: 3 },
			{ id: '2ci', marks: 2 },
			{ id: '2cii', marks: 2 },
			{ id: '2ciii', marks: 1 },
			{ id: '2civ', marks: 3 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 1 },
			{ id: '3bi', marks: 1 },
			{ id: '3bii', marks: 1 },
			{ id: '3biii', marks: 1 },
			{ id: '3c', marks: 4 },
			{ id: '3d', marks: 3 },
			{ id: '3e', marks: 2 },
			{ id: '4a', marks: 4 },
			{ id: '4bi', marks: 1 },
			{ id: '4bii', marks: 2 },
			{ id: '4c', marks: 9 },
			{ id: '4di', marks: 5 },
			{ id: '4dii', marks: 3 },
			{ id: '4ei', marks: 3 },
			{ id: '4eii', marks: 2 },
			{ id: '4fi', marks: 2 },
			{ id: '4fii', marks: 2 },
			{ id: '4fiii', marks: 2 },
			{ id: '5a', marks: 1 },
			{ id: '5b', marks: 5 },
			{ id: '6ai', marks: 2 },
			{ id: '6aii', marks: 3 },
			{ id: '6b', marks: 4 },
			{ id: '7', marks: 12 }
		]
	},
	{
		id: 2,
		subject: 'cs',
		board: 'ocr',
		year: 2023,
		season: 'Summer',
		paper: 'H446/02 Algorithms and programming',
		url: "https://www.ocr.org.uk/Images/703781-question-paper-algorithms-and-programming.pdf",
		markschemeUrl: "https://www.ocr.org.uk/Images/703954-mark-scheme-algorithms-and-programming.pdf",
		questions: [
			{ id: '1ai', marks: 2 },
			{ id: '1aii', marks: 4 },
			{ id: '1iii', marks: 2 },
			{ id: '1iv', marks: 4 },
			{ id: '1v', marks: 4 },
			{ id: '1vi', marks: 2 },
			{ id: '1b', marks: 6 },
			{ id: '2', marks: 9 },
			{ id: '3a', marks: 2 },
			{ id: '3b', marks: 1 },
			{ id: '3c', marks: 2 },
			{ id: '3d', marks: 4 },
			{ id: '3e', marks: 5 },
			{ id: '4i', marks: 1 },
			{ id: '4ii', marks: 1 },
			{ id: '4iii', marks: 1 },
			{ id: '4b', marks: 3 },
			{ id: '4c', marks: 2 },
			{ id: '5a', marks: 3 },
			{ id: '5b', marks: 5 },
			{ id: '6', marks: 6 },
			{ id: '7', marks: 9 },
			{ id: '7bi', marks: 2 },
			{ id: '7bii', marks: 2 },
			{ id: '7ci', marks: 5 },
			{ id: '7cii', marks: 2 },
			{ id: '7d', marks: 6 },
			{ id: '8a', marks: 3 },
			{ id: '8b', marks: 2 },
			{ id: '9ai', marks: 3 },
			{ id: '9aii', marks: 3 },
			{ id: '9bi', marks: 5 },
			{ id: '9bii', marks: 2 },
			{ id: '9biii', marks: 2 },
			{ id: '9c', marks: 5 },
			{ id: '9d', marks: 7 },
			{ id: '9e', marks: 4 },
			{ id: '9f', marks: 9 }
		]
	},
	{
		id: 3,
		subject: 'cs',
		board: 'ocr',
		year: 2022,
		season: 'Summer',
		paper: 'H446/01 Computer Systems',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/676742-question-paper-computer-systems.pdf',
		markschemeUrl: 'https://cdn.savemyexams.com/uploads/2024/04/676943-mark-scheme-computer-systems.pdf',
		questions: [
			{ id: '1ai', marks: 2 },
			{ id: '1aii', marks: 1 },
			{ id: '1bi', marks: 2 },
			{ id: '1bii', marks: 2 },
			{ id: '1ci', marks: 3 },
			{ id: '1cii', marks: 4 },
			{ id: '1ciii', marks: 3 },
			{ id: '1civ', marks: 2 },
			{ id: '1di', marks: 2 },
			{ id: '1dii', marks: 2 },
			{ id: '1diii', marks: 3 },
			{ id: '1e', marks: 12 },
			{ id: '2ai', marks: 1 },
			{ id: '2aii', marks: 2 },
			{ id: '2aiii', marks: 1 },
			{ id: '2aiv', marks: 1 },
			{ id: '2bi', marks: 3 },
			{ id: '2bii', marks: 2 },
			{ id: '2ci', marks: 2 },
			{ id: '2cii', marks: 1 },
			{ id: '2di', marks: 2 },
			{ id: '2dii', marks: 1 },
			{ id: '2diii', marks: 3 },
			{ id: '2div', marks: 1 },
			{ id: '2e', marks: 2 },
			{ id: '2f', marks: 5 },
			{ id: '2gi', marks: 7 },
			{ id: '2gii', marks: 2 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 1 },
			{ id: '3aiii', marks: 3 },
			{ id: '3b', marks: 4 },
			{ id: '3ci', marks: 1 },
			{ id: '3cii', marks: 1 },
			{ id: '3ciii', marks: 1 },
			{ id: '3civ', marks: 1 },
			{ id: '4', marks: 9 },
			{ id: '5ai', marks: 1 },
			{ id: '5aii', marks: 1 },
			{ id: '5aiii', marks: 1 },
			{ id: '5bi', marks: 1 },
			{ id: '5bii', marks: 4 },
			{ id: '5ci', marks: 5 },
			{ id: '5di', marks: 2 },
			{ id: '5ei', marks: 3 },
			{ id: '5eii', marks: 1 },
			{ id: '5eiii', marks: 2 },
			{ id: '5f', marks: 9 },
			{ id: '6ai', marks: 2 },
			{ id: '6aii', marks: 3 },
			{ id: '6aiii', marks: 2 },
			{ id: '6bi', marks: 5 },
			{ id: '6bii', marks: 2 }
		],
		totalMarks: 140
	},
	{
		id: 4,
		subject: 'cs',
		board: 'ocr',
		year: 2022,
		season: 'Summer',
		paper: 'H446/02 Algorithms and programming',
		url: "https://cdn.savemyexams.com/uploads/2024/04/676743-question-paper-algorithms-and-programming.pdf",
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/676743-question-paper-algorithms-and-programming.pdf",
		questions: [
			{ id: '1ai', marks: 2 },
			{ id: '1aii', marks: 4 },
			{ id: '1iii', marks: 2 },
			{ id: '1iv', marks: 4 },
			{ id: '1v', marks: 4 },
			{ id: '1vi', marks: 2 },
			{ id: '1b', marks: 6 },
			{ id: '2', marks: 9 },
			{ id: '3a', marks: 2 },
			{ id: '3b', marks: 1 },
			{ id: '3c', marks: 2 },
			{ id: '3d', marks: 4 },
			{ id: '3e', marks: 5 },
			{ id: '4i', marks: 1 },
			{ id: '4ii', marks: 1 },
			{ id: '4iii', marks: 1 },
			{ id: '4b', marks: 3 },
			{ id: '4c', marks: 2 },
			{ id: '5a', marks: 3 },
			{ id: '5b', marks: 5 },
			{ id: '6', marks: 6 },
			{ id: '7', marks: 9 },
			{ id: '7bi', marks: 2 },
			{ id: '7bii', marks: 2 },
			{ id: '7ci', marks: 5 },
			{ id: '7cii', marks: 2 },
			{ id: '7d', marks: 6 },
			{ id: '8a', marks: 3 },
			{ id: '8b', marks: 2 },
			{ id: '9ai', marks: 3 },
			{ id: '9aii', marks: 3 },
			{ id: '9bi', marks: 5 },
			{ id: '9bii', marks: 2 },
			{ id: '9biii', marks: 2 },
			{ id: '9c', marks: 5 },
			{ id: '9d', marks: 7 },
			{ id: '9e', marks: 4 },
			{ id: '9f', marks: 9 }
		]
	},
	{
		id: 5,
		subject: 'cs',
		board: 'ocr',
		year: 2021,
		season: 'Autumn',
		paper: 'H446/01 Computer Systems',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/666846-question-paper-paper-1-computer-systems.pdf',
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/666849-mark-scheme-paper-1-computer-systems.pdf",
		questions: [
			{ id: '1ai', marks: 2 },
			{ id: '1aii', marks: 4 },
			{ id: '1aiii', marks: 2 },
			{ id: '1b', marks: 3 },
			{ id: '1c', marks: 9 },
			{ id: '1di', marks: 2 },
			{ id: '1dii', marks: 4 },
			{ id: '1diii', marks: 2 },
			{ id: '1div', marks: 5 },
			{ id: '2ai', marks: 1 },
			{ id: '2aii', marks: 1 },
			{ id: '2bi', marks: 4 },
			{ id: '2bii', marks: 3 },
			{ id: '2c', marks: 5 },
			{ id: '3a', marks: 4 },
			{ id: '3b', marks: 3 },
			{ id: '3c', marks: 4 },
			{ id: '3di', marks: 3 },
			{ id: '3dii', marks: 2 },
			{ id: '3ei', marks: 4 },
			{ id: '3eii', marks: 1 },
			{ id: '3eiii', marks: 2 },
			{ id: '4', marks: 9 },
			{ id: '5a', marks: 3 },
			{ id: '5bi', marks: 2 },
			{ id: '5ci', marks: 2 },
			{ id: '5cii', marks: 2 },
			{ id: '5ciii', marks: 4 },
			{ id: '6ai', marks: 2 },
			{ id: '6aii', marks: 2 },
			{ id: '6b', marks: 4 },
			{ id: '6c', marks: 4 },
			{ id: '6d', marks: 12 },
			{ id: '7ai', marks: 1 },
			{ id: '7aii', marks: 4 },
			{ id: '7bi', marks: 4 },
			{ id: '7bii', marks: 3 },
			{ id: '7biii', marks: 2 },
			{ id: '7biv', marks: 2 },
			{ id: '7ci', marks: 3 },
			{ id: '7cii', marks: 5 }
		],
		totalMarks: 140
	},
	{
		id: 6,
		subject: 'cs',
		board: 'ocr',
		year: 2021,
		season: 'Autumn',
		paper: 'H446/02 Algorithms and programming',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/666846-question-paper-paper-2-computer-systems.pdf',
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/666849-mark-scheme-paper-2-computer-systems.pdf",
		questions: [
			{ id: '1a', marks: 3 },
			{ id: '1bi', marks: 2 },
			{ id: '1bii', marks: 3 },
			{ id: '1ci', marks: 2 },
			{ id: '1cii', marks: 8 },
			{ id: '1d', marks: 6 },
			{ id: '1e', marks: 9 },
			{ id: '2ai', marks: 6 },
			{ id: '2aii', marks: 1 },
			{ id: '2b', marks: 6 },
			{ id: '2c', marks: 1 },
			{ id: '3a', marks: 5 },
			{ id: '3b', marks: 2 },
			{ id: '4', marks: 9 },
			{ id: '5a', marks: 1 },
			{ id: '5b', marks: 2 },
			{ id: '5c', marks: 5 },
			{ id: '5d', marks: 6 },
			{ id: '5e', marks: 4 },
			{ id: '5f', marks: 4 },
			{ id: '6a', marks: 4 },
			{ id: '6b', marks: 2 },
			{ id: '7a', marks: 4 },
			{ id: '7b', marks: 5 },
			{ id: '8ai', marks: 3 },
			{ id: '8aii', marks: 2 },
			{ id: '8aiii', marks: 3 },
			{ id: '8bi', marks: 5 },
			{ id: '8bii', marks: 2 },
			{ id: '8biii', marks: 3 },
			{ id: '8biv', marks: 6 },
			{ id: '8bv', marks: 3 },
			{ id: '8c', marks: 9 },
			{ id: '8d', marks: 4 }
		],
		totalMarks: 140
	},
	{
		id: 7,
		subject: 'cs',
		board: 'ocr',
		year: 2020,
		season: 'Autumn',
		paper: 'H446/01 Computer Systems',
		url: "https://cdn.savemyexams.com/uploads/2024/04/h446-01-nov-2020-qp-ocr-a-level-computer-science.pdf",
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/h446-01-nov-2020-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1ai', marks: 3 },
			{ id: '1aii', marks: 2 },
			{ id: '1b', marks: 3 },
			{ id: '1c', marks: 9 },
			{ id: '1di', marks: 4 },
			{ id: '1dii', marks: 3 },
			{ id: '1diii', marks: 4 },
			{ id: '1e', marks: 2 },
			{ id: '2ai', marks: 4 },
			{ id: '2aii', marks: 3 },
			{ id: '2aiii', marks: 3 },
			{ id: '2b', marks: 3 },
			{ id: '2c', marks: 4 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 1 },
			{ id: '3aiii', marks: 1 },
			{ id: '3aiv', marks: 2 },
			{ id: '3b', marks: 5 },
			{ id: '3ci', marks: 2 },
			{ id: '3cii', marks: 2 },
			{ id: '4ai', marks: 3 },
			{ id: '4aii', marks: 2 },
			{ id: '4bi', marks: 2 },
			{ id: '4bii', marks: 4 },
			{ id: '5', marks: 9 },
			{ id: '6', marks: 8 },
			{ id: '7a', marks: 5 },
			{ id: '7b', marks: 6 },
			{ id: '8', marks: 12 },
			{ id: '9ai', marks: 4 },
			{ id: '9aii', marks: 2 },
			{ id: '9aiii', marks: 2 },
			{ id: '9b', marks: 3 },
			{ id: '9c', marks: 4 },
			{ id: '9di', marks: 2 },
			{ id: '9dii', marks: 1 },
			{ id: '9ei', marks: 3 },
			{ id: '9eii', marks: 2 },
			{ id: '9eiii', marks: 2 },
			{ id: '9eiv', marks: 3 }
		],
		totalMarks: 140
	},
	{
		id: 8,
		subject: 'cs',
		board: 'ocr',
		year: 2020,
		season: 'Autumn',
		paper: 'H446/02 Algorithms and programming',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/h446-02-nov-2020-qp-ocr-a-level-computer-science.pdf',
		markschemeUrl:"https://cdn.savemyexams.com/uploads/2024/04/h446-02-nov-2020-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1a', marks: 3 },
			{ id: '1b', marks: 1 },
			{ id: '1c', marks: 1 },
			{ id: '1d', marks: 4 },
			{ id: '1ei', marks: 3 },
			{ id: '1eii', marks: 3 },
			{ id: '1f', marks: 4 },
			{ id: '2a', marks: 4 },
			{ id: '2b', marks: 9 },
			{ id: '3a', marks: 5 },
			{ id: '3b', marks: 1 },
			{ id: '3c', marks: 4 },
			{ id: '3d', marks: 6 },
			{ id: '4a', marks: 2 },
			{ id: '4b', marks: 3 },
			{ id: '4c', marks: 9 },
			{ id: '4d', marks: 6 },
			{ id: '5a', marks: 2 },
			{ id: '5b', marks: 5 },
			{ id: '5ci', marks: 5 },
			{ id: '5cii', marks: 6 },
			{ id: '5ciii', marks: 8 },
			{ id: '5d', marks: 3 },
			{ id: '5e', marks: 3 },
			{ id: '6ai', marks: 2 },
			{ id: '6aii', marks: 1 },
			{ id: '6aiii', marks: 4 },
			{ id: '6bi', marks: 4 },
			{ id: '6bii', marks: 2 },
			{ id: '6c', marks: 6 },
			{ id: '6di', marks: 3 },
			{ id: '6dii', marks: 6 },
			{ id: '6e', marks: 12 }
		],
		totalMarks: 140
	},
	{
		id: 9,
		subject: 'cs',
		board: 'ocr',
		year: 2019,
		season: 'Summer',
		paper: 'H446/01 Computer Systems',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/h446-01-june-2019-qp-ocr-a-level-computer-science.pdf',
		markschemeUrl:"https://cdn.savemyexams.com/uploads/2024/04/h446-01-june-2019-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1a', marks: 4 },
			{ id: '1b', marks: 2 },
			{ id: '1ci', marks: 2 },
			{ id: '1cii', marks: 3 },
			{ id: '1d', marks: 2 },
			{ id: '2a', marks: 1 },
			{ id: '2b', marks: 2 },
			{ id: '2c', marks: 3 },
			{ id: '2d', marks: 5 },
			{ id: '3a', marks: 3 },
			{ id: '3b', marks: 1 },
			{ id: '3c', marks: 2 },
			{ id: '3d', marks: 1 },
			{ id: '3e', marks: 2 },
			{ id: '4a', marks: 2 },
			{ id: '4b', marks: 1 },
			{ id: '4c', marks: 1 },
			{ id: '4d', marks: 4 },
			{ id: '4e', marks: 3 },
			{ id: '5a', marks: 1 },
			{ id: '5b', marks: 1 },
			{ id: '5c', marks: 5 },
			{ id: '5d', marks: 4 },
			{ id: '5e', marks: 12 },
			{ id: '6a', marks: 2 },
			{ id: '6b', marks: 1 },
			{ id: '6c', marks: 4 },
			{ id: '6d', marks: 3 },
			{ id: '6e', marks: 2 },
			{ id: '6f', marks: 2 },
			{ id: '7a', marks: 3 },
			{ id: '7bi', marks: 1 },
			{ id: '7bii', marks: 2 },
			{ id: '7c', marks: 2 },
			{ id: '7d', marks: 3 },
			{ id: '7e', marks: 2 },
			{ id: '8a', marks: 1 },
			{ id: '8b', marks: 1 },
			{ id: '8c', marks: 1 },
			{ id: '8d', marks: 1 },
			{ id: '8e', marks: 2 },
			{ id: '8f', marks: 3 },
			{ id: '8g', marks: 1 },
			{ id: '9', marks: 9 },
			{ id: '10a', marks: 1 },
			{ id: '10b', marks: 2 },
			{ id: '10c', marks: 2 },
			{ id: '10d', marks: 2 },
			{ id: '10e', marks: 3 },
			{ id: '10f', marks: 4 },
			{ id: '11a', marks: 9 },
			{ id: '11b', marks: 2 },
			{ id: '11c', marks: 2 }
		],
		totalMarks: 140
	},
	{
		id: 10,
		subject: 'cs',
		board: 'ocr',
		year: 2019,
		season: 'Summer',
		paper: 'H446/02 Algorithms and programming',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2019-qp-ocr-a-level-computer-science.pdf',
		markschemeUrl: 'https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2019-ms-ocr-a-level-computer-science.pdf',
		questions: [
			{ id: '1a', marks: 2 },
			{ id: '1bi', marks: 1 },
			{ id: '1bii', marks: 3 },
			{ id: '1biii', marks: 5 },
			{ id: '1biv', marks: 6 },
			{ id: '2ai', marks: 1 },
			{ id: '2aii', marks: 3 },
			{ id: '2aiii', marks: 4 },
			{ id: '2bi', marks: 2 },
			{ id: '2bii', marks: 3 },
			{ id: '2biii', marks: 4 },
			{ id: '2biv', marks: 5 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 2 },
			{ id: '3aiii', marks: 1 },
			{ id: '3aiv', marks: 2 },
			{ id: '3av', marks: 2 },
			{ id: '3b', marks: 3 },
			{ id: '3ci', marks: 2 },
			{ id: '3cii', marks: 4 },
			{ id: '4a', marks: 2 },
			{ id: '4bi', marks: 6 },
			{ id: '4bii', marks: 2 },
			{ id: '4biii', marks: 2 },
			{ id: '4c', marks: 6 },
			{ id: '4d', marks: 9 },
			{ id: '5a', marks: 6 },
			{ id: '5b', marks: 2 },
			{ id: '6', marks: 9 },
			{ id: '7ai', marks: 2 },
			{ id: '7aii', marks: 3 },
			{ id: '7aiii', marks: 3 },
			{ id: '7bi', marks: 4 },
			{ id: '7bii', marks: 5 },
			{ id: '7biii', marks: 4 },
			{ id: '7biv', marks: 4 },
			{ id: '7bv', marks: 6 },
			{ id: '7c', marks: 9 }
		],
		totalMarks: 140
	},
	{
		id: 11,
		subject: 'cs',
		board: 'ocr',
		year: 2018,
		season: 'Summer',
		paper: 'H446/01 Computer Systems',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/h446-01-june-2018-qp-ocr-a-level-computer-science.pdf',
		markschemeUrl: 'https://cdn.savemyexams.com/uploads/2024/04/h446-01-june-2018-ms-ocr-a-level-computer-science.pdf',
		questions: [
			{ id: '1ai', marks: 2 },
			{ id: '1aii', marks: 2 },
			{ id: '1bi', marks: 2 },
			{ id: '1bii', marks: 6 },
			{ id: '1biii', marks: 3 },
			{ id: '1biv', marks: 9 },
			{ id: '2ai', marks: 3 },
			{ id: '2aii', marks: 1 },
			{ id: '2aiii', marks: 3 },
			{ id: '2bi', marks: 5 },
			{ id: '2bii', marks: 3 },
			{ id: '2biii', marks: 3 },
			{ id: '3a', marks: 2 },
			{ id: '3b', marks: 3 },
			{ id: '3ci', marks: 1 },
			{ id: '3cii', marks: 1 },
			{ id: '3di', marks: 2 },
			{ id: '3dii', marks: 2 },
			{ id: '3diii', marks: 2 },
			{ id: '3e', marks: 2 },
			{ id: '4a', marks: 2 },
			{ id: '4bi', marks: 2 },
			{ id: '4bii', marks: 4 },
			{ id: '5a', marks: 2 },
			{ id: '5bi', marks: 2 },
			{ id: '5bii', marks: 2 },
			{ id: '5c', marks: 2 },
			{ id: '6', marks: 12 },
			{ id: '7a', marks: 3 },
			{ id: '7bi', marks: 2 },
			{ id: '7bii', marks: 2 },
			{ id: '7biii', marks: 2 },
			{ id: '7c', marks: 5 },
			{ id: '7d', marks: 2 },
			{ id: '8a', marks: 2 },
			{ id: '8b', marks: 2 },
			{ id: '8c', marks: 4 },
			{ id: '8d', marks: 9 },
			{ id: '9a', marks: 2 },
			{ id: '9b', marks: 2 },
			{ id: '9c', marks: 2 },
			{ id: '9d', marks: 3 },
			{ id: '9e', marks: 4 },
			{ id: '9f', marks: 1 },
			{ id: '9g', marks: 1 },
			{ id: '10a', marks: 2 },
			{ id: '10b', marks: 5 }
		],
		totalMarks: 140
	},
	{
		id: 12,
		subject: 'cs',
		board: 'ocr',
		year: 2018,
		season: 'Summer',
		paper: 'H446/02 Algorithms and programming',
		url: 'https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2018-qp-ocr-a-level-computer-science.pdf',
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2019-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1a', marks: 3 },
			{ id: '1b', marks: 3 },
			{ id: '1ci', marks: 5 },
			{ id: '1cii', marks: 2 },
			{ id: '2ai', marks: 2 },
			{ id: '2aii', marks: 1 },
			{ id: '2bi', marks: 1 },
			{ id: '2bii', marks: 4 },
			{ id: '2ci', marks: 1 },
			{ id: '2cii', marks: 1 },
			{ id: '2d', marks: 2 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 2 },
			{ id: '3aiii', marks: 2 },
			{ id: '3b', marks: 7 },
			{ id: '3c', marks: 9 },
			{ id: '3d', marks: 6 },
			{ id: '4a', marks: 6 },
			{ id: '4b', marks: 2 },
			{ id: '4c', marks: 9 },
			{ id: '4d', marks: 2 },
			{ id: '5a', marks: 4 },
			{ id: '5bi', marks: 4 },
			{ id: '5bii', marks: 2 },
			{ id: '5c', marks: 3 },
			{ id: '5di', marks: 5 },
			{ id: '5dii', marks: 7 },
			{ id: '5diii', marks: 4 },
			{ id: '6ai', marks: 3 },
			{ id: '6aii', marks: 5 },
			{ id: '6aiii', marks: 3 },
			{ id: '6bi', marks: 2 },
			{ id: '6bii', marks: 2 },
			{ id: '6biii', marks: 2 },
			{ id: '6biv', marks: 6 },
			{ id: '6bv', marks: 1 },
			{ id: '6bvi', marks: 5 },
			{ id: '6bvii', marks: 2 },
			{ id: '6c', marks: 9 }
		],
		totalMarks: 140
	},
	{
		id: 13,
		subject: 'cs',
		board: 'ocr',
		year: 2017,
		season: 'Summer',
		paper: 'H446/01 Computer Systems',
		url: "https://cdn.savemyexams.com/uploads/2022/02/h446-01-june-2017-qp-ocr-a-level-computer-science.pdf",
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2022/02/h446-01-june-2017-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1ai', marks: 1 },
			{ id: '1aii', marks: 2 },
			{ id: '1aiii', marks: 1 },
			{ id: '1bi', marks: 4 },
			{ id: '1bii', marks: 2 },
			{ id: '1ci', marks: 2 },
			{ id: '1cii', marks: 1 },
			{ id: '1ciii', marks: 1 },
			{ id: '2ai', marks: 3 },
			{ id: '2aii', marks: 4 },
			{ id: '2b', marks: 4 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 3 },
			{ id: '3b', marks: 12 },
			{ id: '4a', marks: 3 },
			{ id: '4bi', marks: 4 },
			{ id: '4bii', marks: 2 },
			{ id: '4c', marks: 2 },
			{ id: '5ai', marks: 3 },
			{ id: '5aii', marks: 3 },
			{ id: '5bi', marks: 1 },
			{ id: '5bii', marks: 1 },
			{ id: '5biii', marks: 1 },
			{ id: '5biv', marks: 1 },
			{ id: '5bv', marks: 2 },
			{ id: '6ai', marks: 1 },
			{ id: '6aii', marks: 1 },
			{ id: '6bi', marks: 1 },
			{ id: '6bii', marks: 1 },
			{ id: '6c', marks: 2 },
			{ id: '6d', marks: 6 },
			{ id: '7a', marks: 2 },
			{ id: '7bi', marks: 1 },
			{ id: '7bii', marks: 2 },
			{ id: '7c', marks: 3 },
			{ id: '7d', marks: 3 },
			{ id: '7e', marks: 4 },
			{ id: '8', marks: 9 },
			{ id: '9a', marks: 2 },
			{ id: '9b', marks: 6 },
			{ id: '9ci', marks: 1 },
			{ id: '9cii', marks: 1 },
			{ id: '9ciii', marks: 1 },
			{ id: '10a', marks: 4 },
			{ id: '10b', marks: 6 },
			{ id: '10c', marks: 1 },
			{ id: '10di', marks: 2 },
			{ id: '10dii', marks: 9 },
			{ id: '11a', marks: 3 },
			{ id: '11b', marks: 4 }
		],
		totalMarks: 140
	},
	{
		id: 14,
		subject: 'cs',
		board: 'ocr',
		year: 2017,
		season: 'Summer',
		paper: 'H446/02 Algorithms and programming',
		url: "https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2017-qp-ocr-a-level-computer-science.pdf",
		markschemeUrl: "https://cdn.savemyexams.com/uploads/2024/04/h446-02-june-2017-ms-ocr-a-level-computer-science.pdf",
		questions: [
			{ id: '1ai', marks: 3 },
			{ id: '1aii', marks: 6 },
			{ id: '1bi', marks: 1 },
			{ id: '1bii', marks: 3 },
			{ id: '1c', marks: 9 },
			{ id: '2a', marks: 2 },
			{ id: '2bi', marks: 2 },
			{ id: '2bii', marks: 3 },
			{ id: '2ci', marks: 1 },
			{ id: '2cii', marks: 3 },
			{ id: '2ciii', marks: 2 },
			{ id: '2civ', marks: 4 },
			{ id: '2d', marks: 3 },
			{ id: '2e', marks: 6 },
			{ id: '2f', marks: 9 },
			{ id: '3ai', marks: 1 },
			{ id: '3aii', marks: 4 },
			{ id: '3b', marks: 4 },
			{ id: '3c', marks: 5 },
			{ id: '3d', marks: 5 },
			{ id: '4a', marks: 1 },
			{ id: '4bi', marks: 4 },
			{ id: '4bii', marks: 6 },
			{ id: '4biii', marks: 3 },
			{ id: '5a', marks: 1 },
			{ id: '5b', marks: 5 },
			{ id: '5c', marks: 4 },
			{ id: '6a', marks: 3 },
			{ id: '6bi', marks: 2 },
			{ id: '6bii', marks: 6 },
			{ id: '6ci', marks: 3 },
			{ id: '6cii', marks: 3 },
			{ id: '6di', marks: 4 },
			{ id: '6dii', marks: 2 },
			{ id: '6diii', marks: 5 },
			{ id: '6e', marks: 9 },
			{ id: '6fi', marks: 1 },
			{ id: '6fii', marks: 2 }
		],
		totalMarks: 140
	},
	{
		id: 15,
		subject: 'maths',
		board: 'edexcel',
		year: 2017,
		season: 'Sample',
		paper: '9MA0/01 Pure Mathematics 1',
		url: 'https://cdn.savemyexams.com/uploads/2022/12/edexcel-al-maths-specimen-p1-qp.pdf',
		markschemeUrl: 'https://cdn.savemyexams.com/uploads/2022/12/edexcel-al-maths-specimen-p1-ms.pdf',
		questions: [
			{ id: '1a', marks: 3 },
			{ id: '1b', marks: 2 },
			{ id: '1c', marks: 2 },
			{ id: '2a', marks: 2 },
			{ id: '2b', marks: 3 },
			{ id: '3a', marks: 2 },
			{ id: '3b', marks: 2 },
			{ id: '4', marks: 4 },
			{ id: '5', marks: 3 },
			{ id: '6ai', marks: 1 },
			{ id: '6aii', marks: 1 },
			{ id: '6bi', marks: 4 },
			{ id: '6bii', marks: 1 },
			{ id: '7', marks: 5 },
			{ id: '8a', marks: 2 },
			{ id: '8b', marks: 2 },
			{ id: '8c', marks: 2 },
			{ id: '9a', marks: 4 },
			{ id: '9b', marks: 1 },
			{ id: '10', marks: 5 },
			{ id: '11a', marks: 3 },
			{ id: '11b', marks: 1 },
			{ id: '11c', marks: 3 },
			{ id: '11di', marks: 1 },
			{ id: '11dii', marks: 1 },
			{ id: '12a', marks: 2 },
			{ id: '12b', marks: 4 },
			{ id: '12c', marks: 2 },
			{ id: '12d', marks: 1 },
			{ id: '13a', marks: 2 },
			{ id: '13b', marks: 5 },
			{ id: '13c', marks: 6 },
			{ id: '14a', marks: 3 },
			{ id: '14b', marks: 1 },
			{ id: '14c', marks: 6 },
			{ id: '15a', marks: 4 },
			{ id: '15bi', marks: 2 },
			{ id: '15bii', marks: 2 }
		],
		totalMarks: 100
	}
];
